package cafe;
import java.sql.*;



public class bill extends javax.swing.JFrame {
    
   


  
        
         public bill(int spinnerValue,int spinnerValue2,int spinnerValue3,int spinnerValue4,int spinnerValue5,int spinnerValue6,int SubTot)
         {
           

        initComponents();
       jTextArea.setText(String.valueOf(spinnerValue));
       jTextArea.setText(String.valueOf(spinnerValue2));
        jTextArea.setText(String.valueOf(spinnerValue3));
         jTextArea.setText(String.valueOf(spinnerValue4));
         jTextArea.setText(String.valueOf(spinnerValue5));
         jTextArea.setText(String.valueOf(spinnerValue6));
          jTextFieldTotal.setText(String.valueOf(SubTot));
        jTextArea.append("\n\n\n\nName:Garlic Bread    \tQuantity :  " + spinnerValue  + "\t\tPrice : Rs 200");
        jTextArea.append("\nName:Sandwich              \tQuantity :  " + spinnerValue2 + "\t\tPrice : Rs 50 ");
        jTextArea.append("\nName:Pastry                \tQuantity :  " + spinnerValue3 + "\t\tPrice : Rs 120");
        jTextArea.append("\nName:Salad Bowl            \tQuantity :  " + spinnerValue4 + "\t\tPrice : Rs 100");
        jTextArea.append("\nName:Waffles               \tQuantity :  " + spinnerValue5 + "\t\tPrice : Rs 160");
        jTextArea.append("\nName:Tacos                 \tQuantity :  " + spinnerValue6 + "\t\tPrice : Rs 180");
        jTextFieldTotal.setText("Rs " +SubTot);

                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelTotal = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Pristina", 1, 18)); // NOI18N
        jLabel2.setText("Enter Customer Name to Print :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 620, 200, 40));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 620, 160, 30));

        jLabel3.setFont(new java.awt.Font("Palace Script MT", 0, 48)); // NOI18N
        jLabel3.setText("La Ratatouille");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 200, 60));

        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 660, -1, -1));

        jLabelTotal.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        jLabelTotal.setText("Total    : ");
        getContentPane().add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, 80, -1));
        getContentPane().add(jTextFieldTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 570, 120, 30));

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 500, 610));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Anuj\\Downloads\\download (2) (1).gif")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name;
        String Total;
        try
        {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/test?" +"user=root");
        PreparedStatement pst;
            pst=conn.prepareStatement("insert into bill values(?,?)");
            name=(jTextField1.getText());
            Total=jTextFieldTotal.getText();
            pst.setString(1,name);
            pst.setString(2,Total);
            pst.executeUpdate();
     }
        catch(Exception e)
        {
        System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           new bill(0,0,0,0,0,0,0).setVisible(true);
           
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables
}
